name: C/C++ CI

on:
  push:
    branches: [ maint/maint-56 ]
  pull_request:
    branches: [ maint/maint-56 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cd icu4c/source/ && ./runConfigureICU Linux --disable-renaming
    - name: make
      run: cd icu4c/source/ && make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
