name: Publish package to GitHub Packages
on:
  push:
    branches:
      - '*' # FOR TESTING FOR NOW!!
#   release:
#     types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: icu4j ant releaseCLDR
        run: ant -noinput releaseCLDR -f icu4j/build.xml
      # - name: Publish package
      #   run: mvn -B deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
